machines = {
  "RabbitMQ" => { :ip => "192.168.56.12", :ssh_port => 2200 },
  "Receiver1" => { :ip => "192.168.56.14", :ssh_port => 2220 },
  "Receiver2" => { :ip => "192.168.56.15", :ssh_port => 2220 },
  "Sender" => { :ip => "192.168.56.13", :ssh_port => 2222 },
}

Vagrant.configure("2") do |config|
    
    machines.each_with_index do |(hostname, info), index|
      config.vm.define hostname do |cfg|
        cfg.vm.provider :virtualbox do |vb, override|
          config.vm.box = "ubuntu/bionic64"
          override.vm.network "private_network", ip: "#{info[:ip]}"
          override.vm.network "forwarded_port", guest: 22, host: "#{info[:ssh_port]}", id: "ssh", auto_correct: true
          override.vm.hostname = hostname
          vb.name = hostname
        end
      end
    end
  
    #Ansible
    config.vm.provision "ansible" do |ansible|
          ansible.inventory_path = 'hosts'
          ansible.verbose = 'vvv'
          ansible.playbook = 'playbooks/servers.yml'
    end
end

